cassandra = Customer.create(name: "Cassandra Montoya", preference: "Indian", budget: 10, location: "Downtown")
chantal = Customer.create(name: "Chantal Wallace", preference: "Chinese", budget: 25,  location: "SW Houston")
nadia = Customer.create(name: "Nadia Nik", preference: "Mexican", budget: 8, location: "Eastside")
michael = Customer.create(name: "Michael Yeroshalmi" , preference: "American" , budget: 100 , location: "SW Houston")
shamss = Customer.create(name: "Shamss Hammami" , preference: "Ethiopian" , budget: 20, location: "Montrose")
amanda = Customer.create(name: "Amanda Atzil" , preference: "Mexican" , budget: 10, location: "The Heights")
dora = Customer.create(name: "Dora Johnson", preference: "Vegan" , budget: 25, location: "Third Ward" )
olivia = Customer.create(name: "Olivia Bent" , preference: "Chinese", budget: 5, location: "Eastside" )
alex = Customer.create(name: "Alex Espinoza", preference: "Indian" , budget: 15 , location: "Third Ward" )
abi = Customer.create(name: "Abi Martin" , preference: "Ethiopian", budget: 75, location: "Downtown" )

bombay = Restaurant.create(name: "Bombay Pizza", opening_time: "10:30", closing_time: "22:00", type: "Indian", affordability: "Affordable", location: "Downtown")
green = Restaurant.create(name: "Green Seed Vegan Cafe", opening_time: "11:00" , closing_time: "20:00" , type: "Vegan" , affordability: "Expensive", location: "Third Ward" )
doshi = Restaurant.create(name:"Doshi House" , opening_time: "08:00" , closing_time: "17:00" , type: "Indian" , affordability: "Affordable" , location: "Third Ward" )
fufu = Restaurant.create(name: "Fufu Cafe", opening_time: "11:00" , closing_time: "02:00" , type: "Chinese" , affordability: "Expensive" , location: "SW Houston")
chachos = Restaurant.create(name: "Chachos" , opening_time: "00:00", closing_time: "23:59" , type: "Mexican", affordability: "Cheap" , location: "Eastside")
blue_nile = Restaurant.create(name: "The Blue Nile", opening_time: "11:00", closing_time: "23:00", type: "Ethiopian", affordability: "Expensive", location: "Montrose" )
dim_sum = Restaurant.create(name: "Dim Sum King"  , opening_time: "09:30", closing_time: "21:00", type: "Chinese" , affordability: "Cheap", location: "SW Houston")
 onion_creek = Restaurant.create(name:"Onion Creek Cafe" , opening_time: "07:00", closing_time: "24:00", type: "American", affordability: "Affordable" , location: "The Heights" )
houstons = Restaurant.create(name: "Houston's", opening_time: "11:00" , closing_time: "21:30", type: "American" , affordability: "Expensive", location: "Downtown")
lucys = Restaurant.create(name: "Lucy's Ethiopian Restaurant" , opening_time: "11:00", closing_time: "23:00", type: "Ethiopian", affordability: "Affordable", location: "Eastside")


order_1 = Order.create(customer: "Cassandra Montoya", restaurant: "Bombay Pizza")
order_2 = Order.create(customer: "Chantal Wallace", restaurant: "Fufu Cafe")
order_3 = Order.create(customer: "Nadia Nik", restaurant: "Chachos")
order_4 = Order.create(customer: "Michael Yeroshalmi", restaurant: "Houston's")
order_5 = Order.create(customer: "Shamss Hammami", restaurant: "The Blue Nile")
order_6 = Order.create(customer: "Amanda Atzil", restaurant: "Chachos")
order_7 = Order.create(customer: "Dora Johnson", restaurant: "Green Seed Vegan Cafe")
order_8 = Order.create(customer: "Olivia Bent", restaurant: "Dim Sum King")
order_9 = Order.create(customer: "Alex Espinoza", restaurant: "Doshi House")
order_10 = Order.create(customer: "Abi Martin", restaurant: "Lucy's Ethiopian Restaurant")
