Customer.create(name: "Cassandra Montoya", preference: "Indian", budget: 10, location: "Downtown")
Customer.create(name: "Chantal Wallace", preference: "Chinese", budget: 25,  location: "SW Houston")
Customer.create(name: "Nadia Nik", preference: "Mexican", budget: 8, location: "Eastside")
Customer.create(name: "Michael Yeroshalmi" , preference: "American" , budget: 100 , location: "SW Houston")
Customer.create(name: "Shamss Hammami" , preference: "Ethiopian" , budget: 20, location: "Montrose")
Customer.create(name: "Amanda Atzil" , preference: "Mexican" , budget: 10, location: "The Heights")
Customer.create(name: "Dora Johnson", preference: "Vegan" , budget: 25, location: "Third Ward" )
Customer.create(name: "Olivia Bent" , preference: "Chinese", budget: 5, location: "Eastside" )
Customer.create(name: "Alex Espinoza", preference: "Indian" , budget: 15 , location: "Third Ward" )
Customer.create(name: "Abi Martin" , preference: "Ethiopian", budget: 75, location: "Downtown" )

Restaurant.create(name: "Bombay Pizza", opening_time: "10:30", closing_time: "22:00", type: "Indian", affordability: "Affordable", location: "Downtown")
Restaurant.create(name: "Green Seed Vegan Cafe", opening_time: "11:00" , closing_time: "20:00" , type: "Vegan" , affordability: "Expensive", location: "Third Ward" )
Restaurant.create(name:"Doshi House" , opening_time: "08:00" , closing_time: "17:00" , type: "Indian" , affordability: "Affordable" , location: "Third Ward" )
Restaurant.create(name: "Fufu Cafe", opening_time: "11:00" , closing_time: "02:00" , type: "Chinese" , affordability: "Expensive" , location: "SW Houston")
Restaurant.create(name: "Chachos" , opening_time: "00:00", closing_time: "23:59" , type: "Mexican", affordability: "Cheap" , location: "Eastside")
Restaurant.create(name: "The Blue Nile", opening_time: "11:00", closing_time: "23:00", type: "Ethiopian", affordability: "Expensive", location: "Montrose" )
Restaurant.create(name: "Dim Sum King"  , opening_time: "09:30", closing_time: "21:00", type: "Chinese" , affordability: "Cheap", location: "SW Houston")
Restaurant.create(name:"Onion Creek Cafe" , opening_time: "07:00", closing_time: "24:00", type: "American", affordability: "Affordable" , location: "The Heights" )
Restaurant.create(name: "Houston's", opening_time: "11:00" , closing_time: "21:30", type: "American" , affordability: "Expensive", location: "Downtown")
Restaurant.create(name: "Lucy's Ethiopian Restaurant" , opening_time: "11:00", closing_time: "23:00", type: "Ethiopian", affordability: "Affordable", location: "Eastside")


Order.create(customer: "Cassandra Montoya", restaurant: "Bombay Pizza")
Order.create(customer: "Chantal Wallace", restaurant: "Fufu Cafe")
Order.create(customer: "Nadia Nik", restaurant: "Chachos")
Order.create(customer: "Michael Yeroshalmi", restaurant: "Houston's")
Order.create(customer: "Shamss Hammami", restaurant: "The Blue Nile")
Order.create(customer: "Amanda Atzil", restaurant: "Chachos")
Order.create(customer: "Dora Johnson", restaurant: "Green Seed Vegan Cafe")
Order.create(customer: "Olivia Bent", restaurant: "Dim Sum King")
Order.create(customer: "Alex Espinoza", restaurant: "Doshi House")
Order.create(customer: "Abi Martin", restaurant: "Lucy's Ethiopian Restaurant")
